name: Auto Image Rebuild
on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

jobs:
  build-latest:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Regular Docker Image
        uses: docker/build-push-action@v4
        with:
          context: "${{ github.workspace }}"
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  build-alpine:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Regular Docker Image
        uses: docker/build-push-action@v4
        with:
          context: "${{ github.workspace }}"
          push: true
          tags: ghcr.io/${{ github.repository }}:alpine
          file: "Dockerfile.alpine"
